name: devel

on: 
  push:
    branches-ignore:
      - 'master'
      - 'stable'
    tags-ignore: 
      - '*'
jobs:
    devel:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip-lhapdf
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Build 
          run: make build
        - name: Install 
          run: make install
        - name: Tests
          run: make test
        - name: Build Sphinx
          working-directory: ./docs
          run: make html
