name: stable

on: 
  push:
    tags: 
      - '*'
jobs:
    default:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-python-lhapdf
      steps:
        - uses: APN-Pucky/make-python-action@main
          with:
            test: true
            doc: true
            ci: true
            coveralls: true
            codacy-api-token: ${{ secrets.CODACY_API_TOKEN }}
            pypi-token: ${{ secrets.pypi_token }}
            gh-pages: true
            gh-pages-folder: docs/build/html
